### ISSUE TITLE
Backdoor in your other repo

### ISSUE THREAD

**Issue by tham-le** [Lucasch1/rankers-server#1]
Hello, 
As I can not open an issue in your other repo  ``test``.
please note that there is a backdoor in this code. please dont execute in your computer. 
this is a linkedin post to explain everything. you can see it by yourself by looking for ``.svn/index'``.
https://www.linkedin.com/posts/franco-aguilera-2583685a_the-code-challenge-scam-they-tried-to-hack-activity-7270114822950703107-K3DW?utm_source=share&utm_medium=member_desktop

**Comment by Lucasch1** [comment]
Hey! Tks for the warnning! Do you have more info about it, what info they get and how? Asking to know if i should clean all my computer or if it's something that happens only while running the repo code? I had already started the backend and frontend...

**Comment by tham-le** [comment]
Hello, I don't really know more about this. Maybe you should add in the LinkedIn post, there are people that know things that are in the comment section
